#!/usr/bin/env bash
# Installs and setup haproxy

apt-get update -y
apt-get install haproxy -y

# edit config file
echo "
   listen 455194-lb-01
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 455194-web-01     100.26.171.178:80 check
   server 455194-web-02 	52.91.135.187:80 check
" | tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" |  tee -a /etc/default/haproxy
service haproxy start
