#!/usr/bin/env bash
# Installs and setup haproxy

apt-get update -y
apt-get install haproxy -y

# edit config file
echo "
   listen 430875-lb-01
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 430875-web-01     18.209.224.89:80 check
   server 430875-web-02 	34.227.90.0:80 check
" | tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" |  tee -a /etc/default/haproxy
service haproxy start
