#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd
#    username
#    user id
#    Home directory path for the user



while IFS=: read -r username _ uid _ _ home _; do
    echo "$username:$uid:$home"
done < /etc/passwd
