#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd,
# using the while loop + IFS

while IFS=: read -r username _ uid gid info home shell; do
    password="x" # Default password
    if [ -n "$info" ]; then
        password="$info"
    fi
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
