#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

count=1

while [ $count -le 20 ]
do
    case $count in
        4)
            echo $count
            echo "bad luck from China"
            ;;
        9)
            echo $count
            echo "bad luck from Japan"
            ;;
        17)
            echo $count
            echo "bad luck from Italy"
            ;;
        *)
            echo $count
            ;;
    esac

    count=$((count + 1))
done


#-------------


count=1
bad_luck_iterations=(4 9 17)

while [ $count -le 20 ]; do
    for i in "${bad_luck_iterations[@]}"; do
        if [ $count -eq $i ]; then
            echo $count
            case $i in
                4) echo "bad luck from China";;
                9) echo "bad luck from Japan";;
                17) echo "bad luck from Italy";;
            esac
            break
        fi
    done

    if [ $count -ne $i ]; then
        echo $count
    fi

    count=$((count + 1))
done

#---------------

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done

