#!/usr/bin/env bash
# Bash script that :
# display hours from 0 to 12
# display minutes from 1 to 59

hour=0
minute=1

while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    while [ $minute -le 59 ]
    do
        echo $minute
        minute=$((minute + 1))
    done
    hour=$((hour + 1))
    minute=1
done

