#!/usr/bin/env bash
# Bash script that :
# display hours from 0 to 12
# display minutes from 1 to 59

hour=0

while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    for minute in {1..59}
    do
        echo "$minute"
    done
    hour=$((hour + 1))
done
