#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

for file in *; do
    # Check if the file is not hidden (does not start with a dot)
    if [[ $file != .* ]]; then
        # Use cut to get the part of the name after the first dash
        name=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name"
    fi
done

#----------------------


list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done

#-----------------

command=$(ls)
for dir in $command
do
    echo "$dir" | cut -d '-' -f2
done